export const continents = [
  {
    id: 0,
    name: "Asia",
    feature: "Disaster Map",
    description: "Live disaster zones and severity mapping.",
    lat: 34,
    lon: 90,
    color: "#ef4444",
  },
  {
    id: 1,
    name: "Africa",
    feature: "SOS & Helplines",
    description: "Emergency contacts and SOS assistance.",
    lat: 1,
    lon: 20,
    color: "#eab308",
  },
  {
    id: 2,
    name: "Europe",
    feature: "Weather & Risk",
    description: "Weather alerts and disaster probability.",
    lat: 50,
    lon: 10,
    color: "#3b82f6",
  },
  {
    id: 3,
    name: "North America",
    feature: "Dashboard",
    description: "Threat analytics and monitoring.",
    lat: 40,
    lon: -100,
    color: "#22c55e",
  },
  {
    id: 4,
    name: "South America",
    feature: "Incident Reports",
    description: "Photo & video based reporting.",
    lat: -15,
    lon: -60,
    color: "#a855f7",
  },
  {
    id: 5,
    name: "Australia",
    feature: "Emergency Alerts",
    description: "Critical alerts and warnings.",
    lat: -25,
    lon: 135,
    color: "#ec4899",
  },
  {
    id: 6,
    name: "Antarctica",
    feature: "Global Monitoring",
    description: "Worldwide disaster awareness.",
    lat: -82,
    lon: 0,
    color: "#22d3ee",
  },
];
